version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
    environment:
      TZ: Asia/Tokyo

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  mysql:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - "./infra/redis:/data"

volumes:
  db-store:
